Crypto++: NullNameValuePairs Class Reference
NullNameValuePairs Class Reference