Crypto++: AuthenticatedSymmetricCipher Class Reference
AuthenticatedSymmetricCipher Class Reference
interface for for one direction (encryption or decryption) of a stream cipher or block cipher mode with authentication
#include <cryptlib.h>