Crypto++: DL_PrivateKey_GFP< GP > Class Template Reference
DL_PrivateKey_GFP< GP > Class Template Reference
DL private key (in GF(p) groups).
#include <gfpcrypt.h>