Crypto++: InvertibleRabinFunction Class Reference
InvertibleRabinFunction Class Reference
_
#include <rabin.h>