Crypto++: BlockTransformation Class Reference
BlockTransformation Class Reference
interface for the data processing part of block ciphers
#include <cryptlib.h>