Crypto++: CBC_CTS_Decryption Class Reference
CBC_CTS_Decryption Class Reference