Crypto++: InvertibleRWFunction Class Reference
InvertibleRWFunction Class Reference
_
#include <rw.h>