Crypto++: PK_Signer Class Reference
PK_Signer Class Reference
interface for public-key signers
#include <cryptlib.h>