Crypto++: DL_GroupParameters_GFP Class Reference
DL_GroupParameters_GFP Class Reference
GF(p) group parameters.
#include <gfpcrypt.h>