Crypto++: RandomNumberStore Class Reference
RandomNumberStore Class Reference
RNG-based implementation of Source interface.
#include <filters.h>