Crypto++: BlockCipher Class Reference
BlockCipher Class Reference
interface for one direction (encryption or decryption) of a block cipher
#include <cryptlib.h>