Crypto++: XTR_DH Class Reference
XTR_DH Class Reference
XTR-DH with key validation.
#include <xtrcrypt.h>