Crypto++: FilterWithInputQueue Class Reference
FilterWithInputQueue Class Reference
_
#include <filters.h>