Crypto++: LUCFunction Class Reference
LUCFunction Class Reference
The LUC function.
#include <luc.h>