Crypto++: AuthenticatedKeyAgreementDomain Class Reference
AuthenticatedKeyAgreementDomain Class Reference
interface for domains of authenticated key agreement protocols
#include <cryptlib.h>