Crypto++: TF_VerifierBase Class Reference
TF_VerifierBase Class Reference
_
#include <pubkey.h>