Crypto++: VMAC_Base Class Reference
VMAC_Base Class Reference
#include <vmac.h>