Crypto++: SimpleKeyAgreementDomain Class Reference
SimpleKeyAgreementDomain Class Reference
interface for domains of simple key agreement protocols
#include <cryptlib.h>