Crypto++: HermeticHashFunctionMAC< T_Hash, T_Info > Class Template Reference
HermeticHashFunctionMAC< T_Hash, T_Info > Class Template Reference
MAC construction using a hermetic hash function.
#include <panama.h>