Crypto++: InvertibleRSAFunction_ISO Class Reference
InvertibleRSAFunction_ISO Class Reference