Crypto++: OutputProxy Class Reference
OutputProxy Class Reference