Crypto++: TTMAC Class Reference
TTMAC Class Reference
Two-Track-MAC
#include <ttmac.h>