Crypto++: RWFunction Class Reference
RWFunction Class Reference
_
#include <rw.h>