Crypto++: ESIGNFunction Class Reference
ESIGNFunction Class Reference
_
#include <esign.h>