Crypto++: DL_GroupParameters< T > Class Template Reference
DL_GroupParameters< T > Class Template Reference
interface for DL group parameters
#include <pubkey.h>