Crypto++: StreamTransformation Class Reference
StreamTransformation Class Reference
interface for the data processing part of stream ciphers
#include <cryptlib.h>