Crypto++: EAX_Final< T_BlockCipher, T_IsEncryption > Class Template Reference
EAX_Final< T_BlockCipher, T_IsEncryption > Class Template Reference
#include <eax.h>