Crypto++: Integer Class Reference
Integer Class Reference
multiple precision integer and basic arithmetics
#include <integer.h>