Crypto++: CryptoParameters Class Reference
CryptoParameters Class Reference
interface for crypto prameters
#include <cryptlib.h>