Crypto++: PK_Verifier Class Reference
PK_Verifier Class Reference
interface for public-key signature verifiers
#include <cryptlib.h>