Crypto++: TF_SignerBase Class Reference
TF_SignerBase Class Reference
_
#include <pubkey.h>