Crypto++: RabinFunction Class Reference
RabinFunction Class Reference
_
#include <rabin.h>