Crypto++: BERSetDecoder Class Reference
BERSetDecoder Class Reference
BER Set Decoder.
#include <asn.h>