Crypto++: PKCS5_PBKDF2_HMAC< T > Class Template Reference
PKCS5_PBKDF2_HMAC< T > Class Template Reference
PBKDF2 from PKCS #5, T should be a HashTransformation class.
#include <pwdbased.h>