Crypto++: ChannelSwitch Class Reference
ChannelSwitch Class Reference
Route input to different and/or multiple channels based on channel ID.
#include <channels.h>