Crypto++: MessageAuthenticationCode Class Reference
MessageAuthenticationCode Class Reference
interface for message authentication codes
#include <cryptlib.h>