Crypto++: CMAC< T > Class Template Reference
CMAC< T > Class Template Reference
CMAC
#include <cmac.h>