Crypto++: BlumBlumShub Class Reference
BlumBlumShub Class Reference
BlumBlumShub with factorization of the modulus.
#include <blumshub.h>