Crypto++: InvertibleESIGNFunction Class Reference
InvertibleESIGNFunction Class Reference
_
#include <esign.h>