Crypto++: SimpleKeyingInterface Class Reference
SimpleKeyingInterface Class Reference
keying interface for crypto algorithms that take byte strings as keys
#include <cryptlib.h>