Crypto++: Gzip Class Reference
Gzip Class Reference
GZIP Compression (RFC 1952).
#include <gzip.h>