Crypto++: PKCS8PrivateKey Class Reference
PKCS8PrivateKey Class Reference
encodes/decodes privateKeyInfo
#include <asn.h>