Crypto++: X509PublicKey Class Reference
X509PublicKey Class Reference
encodes/decodes subjectPublicKeyInfo
#include <asn.h>