Crypto++: DL_PublicKey_EC< EC > Class Template Reference
DL_PublicKey_EC< EC > Class Template Reference
EC public key.
#include <eccrypto.h>