Crypto++: CMAC_Base Class Reference
CMAC_Base Class Reference
_
#include <cmac.h>