Crypto++: RSAFunction_ISO Class Reference
RSAFunction_ISO Class Reference