Crypto++: NameValuePairs Class Reference
NameValuePairs Class Reference
interface for retrieving values given their names
#include <cryptlib.h>