Crypto++: SAFER::Dec Class Reference
SAFER::Dec Class Reference