Crypto++: DSA Struct Reference
DSA Struct Reference
DSA
#include <gfpcrypt.h>